import { useState, useCallback } from 'react';

const usePhraseManager = () => {
  const [phraseInput, setPhraseInput] = useState('');
  const [phrases, setPhrases] = useState([]);

  // Template titles for automatic title suggestions
  const templateTitles = {
    'book-reading': 'Book Reading Challenge Bingo!',
    'acclaimed-books': 'Acclaimed Books Bingo!',
    'hiking': 'Hiking Adventures Bingo!',
    'icebreakers': 'Get to Know You Bingo!',
    'party-icebreakers': 'Party Icebreaker Bingo!',
    'movies-2025': 'Popular Movies Bingo!',
    'summer-bucketlist': 'Summer Bucket List Bingo!',
    'fall-activities': 'Fall Activities Bingo!',
    'winter-activities': 'Winter Activities Bingo!',
    'spring-activities': 'Spring Activities Bingo!',
    'classroom-activities': 'Classroom Fun Bingo!',
    'office-party': 'Office Party Bingo!',
    'wedding-reception': 'Wedding Reception Bingo!',
    'baby-shower': 'Baby Shower Bingo!',
    'travel-experiences': 'Travel Experiences Bingo!',
    'food-adventures': 'Foodie Adventures Bingo!',
    'holiday-traditions': 'Holiday Traditions Bingo!',
    'workout-fitness': 'Fitness Challenge Bingo!',
    'college-life': 'College Life Bingo!',
    'numbers': 'Numbers Bingo!',
    'books-2025': '2025 Books Bingo!',
    'movies-2025-new': '2025 Movies Bingo!',
    'resolutions-2025': '2025 Resolutions Bingo!',
    'trends-2025': '2025 Trends Bingo!',
    'tv-shows-2025': '2025 TV Shows Bingo!',
    'christmas-bucketlist': 'Christmas Bucket List Bingo!',
    'deep-questions': 'Deep Questions Bingo!',
    'family-gathering': 'Family Gathering Bingo!',
    'indoor-winter-adult': 'Indoor Winter Activities (Adult) Bingo!',
    'indoor-winter-family': 'Indoor Winter Activities (Family) Bingo!',
    'outdoor-winter': 'Outdoor Winter Activities Bingo!',
    'outdoor-winter-adult': 'Outdoor Winter Activities (Adult) Bingo!',
    'outdoor-winter-family': 'Outdoor Winter Activities (Family) Bingo!',
    'thanksgiving': 'Thanksgiving Bingo!',
    'ultra-specific-resolutions': 'Ultra Specific Resolutions Bingo!',
    'winter-adult-all': 'Winter Activities (Adult) Bingo!',
    'winter-family-all': 'Winter Activities (Family) Bingo!'
  };

  // Sample data embedded directly to avoid import issues
  const samplePhrases = {
    'book-reading': [
      'A book set in the Pacific Northwest',
      'A novel featuring time travel mishaps',
      'A cozy mystery with a punny title',
      'A book by an author using a pseudonym',
      'A speculative fiction novel published in 2025',
      'A book about a heist or con',
      'A romance where the main characters are rivals',
      'A book with a one-word title',
      'A translated work from a language you don\'t speak',
      'A book with a non-human narrator',
      'A novel inspired by folklore or mythology',
      'A book set in a single day',
      'A story told through letters, emails, or diary entries',
      'A book with a map in the front',
      'A book featuring a librarian or bookseller',
      'A climate fiction ("cli-fi") novel',
      'A book with a color in the title',
      'A locked-room mystery',
      'A book where food plays a central role',
      'A debut novel by a BIPOC author',
      'A book set during a festival or holiday',
      'A novel with a dual timeline',
      'A book recommended by a local bookseller',
      'A story set in a fictional country',
      'A book featuring a road trip',
      'A book with a number in the title',
      'A collection of short stories by different authors',
      'A book about friendship across generations',
      'A book featuring a haunted place',
      'A book with a protagonist over the age of 60',
      'A graphic novel or comic memoir',
      'A book inspired by real historical events',
      'A book that made you laugh out loud',
      'A book featuring a magical animal',
      'A book set on an island',
      'A novel with a twist ending',
      'A book whose cover is your favorite color',
      'A book about music or musicians',
      'A book adapted into a movie or TV show in the last 5 years',
      'A book you meant to read last year but didn\'t'
    ],
    'acclaimed-books': [
      'Demon Copperhead – Barbara Kingsolver',
      'The Underground Railroad – Colson Whitehead',
      'The Wager – David Grann',
      'Severance – Ling Ma',
      'Fourth Wing – Rebecca Yarros',
      'The Deluge – Stephen Markley',
      'How to Say Babylon – Safiya Sinclair',
      'Doppelganger – Naomi Klein',
      'Humanly Possible – Sarah Bakewell',
      'King: A Life – Jonathan Eig',
      'The Kingdom, the Power, and the Glory – Tim Alberta',
      'Land of Milk and Honey – C Pam Zhang',
      'Lone Women – Victor LaValle',
      'Past Lives – Lee Isaac Chung',
      'The Most Secret Memory of Men – Mohamed Mbougar Sarr',
      'The Iliad (Emily Wilson translation)',
      'Ink Blood Sister Scribe – Emma Törzs',
      'Lord of the Flies – William Golding',
      'Invisible Man – Ralph Ellison',
      'Slaughterhouse-Five – Kurt Vonnegut',
      'Deliverance – James Dickey',
      'A Gentleman in Moscow – Amor Towles',
      'A Little Life – Hanya Yanagihara',
      'A Man Called Ove – Fredrik Backman',
      '1984 – George Orwell',
      'The Goldfinch – Donna Tartt',
      'The Night Circus – Erin Morgenstern',
      'The Nickel Boys – Colson Whitehead',
      'The Testaments – Margaret Atwood',
      'The Overstory – Richard Powers',
      'Pachinko – Min Jin Lee',
      'Circe – Madeline Miller',
      'Where the Crawdads Sing – Delia Owens',
      'The Silent Patient – Alex Michaelides',
      'The Girl on the Train – Paula Hawkins',
      'The Hate U Give – Angie Thomas',
      'Normal People – Sally Rooney',
      'The Vanishing Half – Brit Bennett',
      'The Song of Achilles – Madeline Miller',
      'The Seven Husbands of Evelyn Hugo – Taylor Jenkins Reid'
    ],
    'hiking': [
      'Hiked in the rain',
      'Seen a bear or other large wildlife on a trail',
      'Used trekking poles',
      'Gotten lost (even briefly) on a hike',
      'Hiked at sunrise',
      'Hiked at sunset',
      'Camped overnight in the backcountry',
      'Packed out someone else\'s trash',
      'Used a paper map or compass',
      'Tried geocaching',
      'Hiked above 6,000 feet elevation',
      'Crossed a suspension bridge',
      'Slipped and fell in the mud',
      'Used a water filter or purifier',
      'Hiked with a dog',
      'Eaten a freeze-dried meal',
      'Spotted a waterfall on a hike',
      'Hiked in snow',
      'Used a bear canister',
      'Gone on a solo hike',
      'Hiked more than 10 miles in a day',
      'Swam in an alpine lake',
      'Summited a peak',
      'Hiked in another country',
      'Used a GPS app (like AllTrails or Gaia)',
      'Got a blister on a hike',
      'Worn mismatched socks',
      'Hiked in sandals',
      'Brought a friend on their first hike',
      'Seen wildflowers in bloom',
      'Eaten wild berries (safely!)',
      'Hiked to a fire lookout',
      'Forgot an important piece of gear',
      'Made coffee or tea on the trail',
      'Watched a meteor shower while camping',
      'Hiked with a group of 6 or more',
      'Hiked to a hot spring',
      'Been caught in a thunderstorm',
      'Seen mountain goats or marmots',
      'Hiked a trail you\'d recommend to everyone'
    ],
    'icebreakers': [
      'Has worked in more than three industries',
      'Speaks more than two languages',
      'Has a hidden talent',
      'Has worked remotely from another country',
      'Prefers tea over coffee',
      'Has met someone famous',
      'Can play a musical instrument',
      'Has run a marathon or half-marathon',
      'Has a pet (dog, cat, fish, etc.)',
      'Has lived in more than three cities',
      'Is an only child',
      'Loves scary movies',
      'Has performed on stage (music, theater, dance, etc.)',
      'Has a food allergy',
      'Can whistle using fingers',
      'Has binge-watched a TV series in a weekend',
      'Has a collection (stamps, coins, Funko Pops, etc.)',
      'Has been skydiving or bungee jumping',
      'Can solve a Rubik\'s cube',
      'Has read more than 20 books in the past year',
      'Has a favorite karaoke song',
      'Loves spicy food',
      'Has worked in a different country',
      'Has never broken a bone',
      'Is left-handed',
      'Has a twin or is a twin',
      'Has met someone with the same birthday',
      'Has been on a podcast or radio show',
      'Has created a meme',
      'Has made their own bread from scratch',
      'Has won a contest or competition',
      'Has a favorite board game',
      'Has attended a virtual concert',
      'Has taken a cooking class',
      'Has been to a national park in the last year',
      'Has watched a movie more than five times',
      'Has a favorite superhero',
      'Has a go-to productivity hack',
      'Has a favorite motivational quote',
      'Has a unique workspace decoration'
    ],
    'party-icebreakers': [
      'Has sung karaoke in public',
      'Has eaten dessert for breakfast',
      'Can do a magic trick',
      'Has met a celebrity (or someone they consider famous)',
      'Has a go-to dance move',
      'Has tried an unusual food (like escargot or durian)',
      'Can wiggle their ears',
      'Has been on TV or in a newspaper',
      'Has a favorite "guilty pleasure" song',
      'Has gotten a funny sunburn',
      'Has slept outdoors (not camping)',
      'Can do a cartwheel (or claims to)',
      'Has a favorite childhood cartoon',
      'Has gotten lost in a foreign city',
      'Has a collection of something unusual',
      'Has accidentally worn mismatched shoes or socks',
      'Has a party trick (and will show it)',
      'Has a tattoo or wants one',
      'Has made up a word and used it in conversation',
      'Has eaten something straight from the jar',
      'Has given themselves a haircut',
      'Has been to more than 10 concerts',
      'Can whistle a tune',
      'Has a nickname unrelated to their real name',
      'Has been on a spontaneous road trip',
      'Has sent a text to the wrong person',
      'Has a favorite board game',
      'Can name all the planets in order',
      'Has tried a viral internet challenge',
      'Has a favorite meme or viral video',
      'Has won a costume contest',
      'Has performed in front of a crowd',
      'Has a favorite ice cream flavor that\'s not vanilla, chocolate, or strawberry',
      'Has made a prank call',
      'Has stayed up all night for fun',
      'Has made a meal using only a microwave',
      'Has gotten a song stuck in their head for days',
      'Has been mistaken for someone else',
      'Has a favorite "dad joke"',
      'Has worn pajamas in public (on purpose)'
    ],
    'movies-2025': [
      'Barbie',
      'Oppenheimer',
      'Dune: Part Two',
      'Everything Everywhere All at Once',
      'Parasite',
      'Poor Things',
      'The Holdovers',
      'Past Lives',
      'Anatomy of a Fall',
      'Spider-Man: Across the Spider-Verse',
      'Top Gun: Maverick',
      'The Banshees of Inisherin',
      'The Fabelmans',
      'Aftersun',
      'Killers of the Flower Moon',
      'The Zone of Interest',
      'Avatar: The Way of Water',
      'The Super Mario Bros. Movie',
      'Black Panther: Wakanda Forever',
      'Godzilla x Kong: The New Empire',
      'Inside Out 2',
      'Minari',
      'Nomadland',
      'The Power of the Dog',
      'CODA',
      'A Quiet Place',
      'Joker',
      'Jojo Rabbit',
      'Marriage Story',
      '1917',
      'Parasite',
      'La La Land',
      'Moonlight',
      'Mad Max: Fury Road',
      'Get Out',
      'The Shape of Water',
      'The Grand Budapest Hotel',
      'Whiplash',
      'Birdman',
      'Spotlight'
    ],
    'summer-bucketlist': [
      'Watch a movie outdoors (at a drive-in or outdoor screening)',
      'Try a new ice cream flavor',
      'Go on a sunrise or sunset hike',
      'Have a picnic in a park',
      'Visit a local farmers market',
      'Swim in a lake, river, or ocean',
      'Try stand-up paddleboarding or kayaking',
      'Host a backyard barbecue',
      'Attend a summer festival or fair',
      'Go berry picking',
      'Make homemade popsicles',
      'Visit a botanical garden',
      'Read a book in a hammock',
      'Go camping (even if it\'s in your backyard)',
      'Stargaze and spot a constellation',
      'Volunteer at a community event',
      'Take a spontaneous road trip',
      'Visit a new neighborhood or town',
      'Make s\'mores over a campfire',
      'Go to a live outdoor concert',
      'Take a day off to do absolutely nothing',
      'Try geocaching or a scavenger hunt',
      'Ride a bike somewhere scenic',
      'Watch fireworks',
      'Plant something and watch it grow',
      'Make a summer playlist and share it',
      'Go to a water park or splash pad',
      'Try a new summer sport (frisbee golf, beach volleyball, etc.)',
      'Eat a meal al fresco (outdoors)',
      'Visit a museum or art exhibit',
      'Do a random act of kindness',
      'Jump into water fully clothed',
      'Make tie-dye shirts',
      'Visit a rooftop or patio restaurant',
      'Catch a sunrise or sunset from a new spot',
      'Send a postcard to a friend',
      'Take photos of your favorite summer moments',
      'Try a new summer recipe',
      'Have a screen-free day',
      'Make a sandcastle or sculpture'
    ],
    'fall-activities': [
      'Go apple picking at an orchard',
      'Jump in a pile of leaves',
      'Carve a pumpkin',
      'Visit a corn maze',
      'Make homemade apple cider',
      'Go on a fall foliage hike',
      'Attend a harvest festival',
      'Make pumpkin bread or pie',
      'Visit a haunted house',
      'Go to a football game',
      'Rake leaves (and jump in them)',
      'Decorate for Halloween',
      'Make s\'mores around a fire pit',
      'Visit a pumpkin patch',
      'Try a new soup recipe',
      'Go on a hayride',
      'Pick up pine cones for crafts',
      'Make caramel apples',
      'Watch scary movies',
      'Attend Oktoberfest or beer festival',
      'Go camping in fall weather',
      'Make hot chocolate from scratch',
      'Visit a farmers market',
      'Try geocaching in fall colors',
      'Go to a craft fair',
      'Make leaf art or pressing',
      'Attend a bonfire',
      'Go stargazing on a clear fall night',
      'Try a fall-flavored latte',
      'Volunteer at a local charity',
      'Go antique shopping',
      'Make homemade chili',
      'Visit a state park',
      'Try photography of fall scenery',
      'Go to a wine tasting',
      'Make thanksgiving decorations',
      'Attend a parade',
      'Try new fall spices in cooking',
      'Go bird watching during migration',
      'Have a cozy reading day indoors'
    ],
    'winter-activities': [
      'Build a snowman',
      'Go ice skating',
      'Make hot cocoa with marshmallows',
      'Have a snowball fight',
      'Go sledding or tubing',
      'Try skiing or snowboarding',
      'Make snow angels',
      'Attend a holiday market',
      'Go snowshoeing',
      'Build a snow fort',
      'Make homemade soup',
      'Go winter hiking',
      'Try ice fishing',
      'Make holiday cookies',
      'Go to a winter festival',
      'Watch holiday movies',
      'Make a gingerbread house',
      'Go caroling',
      'Try winter photography',
      'Visit a Christmas tree farm',
      'Make paper snowflakes',
      'Go to a hockey game',
      'Try cross-country skiing',
      'Make mulled wine or cider',
      'Go winter camping',
      'Try snowmobiling',
      'Make a fire in the fireplace',
      'Go to a holiday light display',
      'Try indoor rock climbing',
      'Make winter crafts',
      'Go to a museum',
      'Try a new board game',
      'Make homemade bread',
      'Go bowling',
      'Try yoga or meditation',
      'Make winter bird feeders',
      'Go to a spa day',
      'Try cooking a new cuisine',
      'Attend a winter concert',
      'Have a movie marathon weekend'
    ],
    'spring-activities': [
      'Plant a garden',
      'Go on a nature walk',
      'Have a picnic in the park',
      'Clean out winter clothes',
      'Start spring cleaning',
      'Go bird watching',
      'Take photos of blooming flowers',
      'Try outdoor yoga',
      'Go to a farmers market',
      'Plant flowers in pots',
      'Go hiking on a new trail',
      'Have a barbecue',
      'Go biking',
      'Start a herb garden',
      'Go fishing',
      'Attend an outdoor concert',
      'Try paddleboarding',
      'Go camping',
      'Have an outdoor movie night',
      'Try geocaching',
      'Go to a baseball game',
      'Start running outside again',
      'Try outdoor painting or sketching',
      'Go to a festival',
      'Clean and organize the garage',
      'Try a new outdoor sport',
      'Go to a zoo or aquarium',
      'Have a car wash',
      'Try gardening with kids',
      'Go strawberry picking',
      'Attend a wine tasting',
      'Try outdoor photography',
      'Go to a park you\'ve never visited',
      'Try frisbee or disc golf',
      'Have a outdoor breakfast',
      'Go to a craft fair',
      'Try kite flying',
      'Go on a scenic drive',
      'Try outdoor meditation',
      'Have a bonfire'
    ],
    'classroom-activities': [
      'Has been the teacher\'s pet',
      'Has fallen asleep in class',
      'Has forgotten to do homework',
      'Has participated in a science fair',
      'Has been in a school play',
      'Has joined a sports team',
      'Has been class president',
      'Has gotten a perfect attendance award',
      'Has been in detention',
      'Has given a presentation to the class',
      'Has forgotten their lunch money',
      'Has been in the school band or choir',
      'Has tutored another student',
      'Has been on a field trip',
      'Has participated in a debate',
      'Has written for the school newspaper',
      'Has been in student government',
      'Has won a spelling bee',
      'Has been hall monitor',
      'Has organized a school event',
      'Has participated in a talent show',
      'Has been in an academic club',
      'Has done a group project',
      'Has presented a book report',
      'Has participated in career day',
      'Has been in a school competition',
      'Has helped decorate for a dance',
      'Has been a peer mediator',
      'Has participated in spirit week',
      'Has been on the honor roll',
      'Has been in yearbook committee',
      'Has participated in fundraising',
      'Has been a study group leader',
      'Has attended summer school',
      'Has been in art or photography club',
      'Has participated in mock trial',
      'Has been a library assistant',
      'Has done community service for school',
      'Has been in academic olympics',
      'Has graduated with honors'
    ],
    'office-party': [
      'Has worked here longest',
      'Always brings the best snacks',
      'Has the messiest desk',
      'Never misses a deadline',
      'Is always first to arrive',
      'Is last to leave',
      'Has the most plants at their desk',
      'Always knows the latest office gossip',
      'Has the best coffee maker',
      'Is the office tech support',
      'Always forgets to mute on calls',
      'Has won employee of the month',
      'Has the most colorful wardrobe',
      'Is always organizing office events',
      'Has the best lunch spots',
      'Is the office comedian',
      'Has the most awards/certificates',
      'Is always volunteering for projects',
      'Has the cleanest workspace',
      'Is the office photographer',
      'Always remembers birthdays',
      'Has the best work-life balance',
      'Is the office fitness motivator',
      'Has worked in the most departments',
      'Is always planning the next team outing',
      'Has the most creative solutions',
      'Is the office party planner',
      'Has the best parking spot',
      'Is always positive and upbeat',
      'Has the most interesting side hustle',
      'Is the office mentor',
      'Has the best holiday decorations',
      'Is always trying new restaurants',
      'Has the most organized files',
      'Is the office mediator',
      'Has the best presentation skills',
      'Is always learning new skills',
      'Has the most loyal coffee shop',
      'Is the office safety champion',
      'Has the best work anniversary story'
    ],
    'wedding-reception': [
      'Knows the bride from college',
      'Knows the groom from work',
      'Is related to the bride',
      'Is related to the groom',
      'Has been married longer than the couple',
      'Is single and ready to mingle',
      'Has caught the bouquet before',
      'Has been in a wedding party',
      'Is wearing something borrowed',
      'Has known the couple since they met',
      'Is from out of town',
      'Has kids at home',
      'Is the youngest guest here',
      'Is celebrating an anniversary this year',
      'Has been to more than 10 weddings',
      'Is wearing brand new shoes',
      'Has given a toast at a wedding',
      'Is here with a plus-one',
      'Has been married at this venue',
      'Is planning their own wedding',
      'Has the same anniversary month',
      'Is wearing the couple\'s wedding colors',
      'Has traveled the farthest to be here',
      'Has known the bride/groom since childhood',
      'Is wearing something old',
      'Has been to the bachelor/bachelorette party',
      'Is here without their spouse',
      'Has been married by the same officiant',
      'Is wearing something blue',
      'Has the same first name as bride/groom',
      'Is a coworker of the couple',
      'Has been divorced',
      'Is celebrating a milestone birthday this year',
      'Has eloped themselves',
      'Is wearing something new',
      'Has given relationship advice to the couple',
      'Is here as someone\'s date',
      'Has been married in the same month',
      'Has children older than the couple',
      'Has never been married'
    ],
    'baby-shower': [
      'Is expecting their first baby',
      'Has more than 3 children',
      'Is a grandparent',
      'Is the baby\'s godparent',
      'Has twin children',
      'Is a single parent',
      'Has adopted a child',
      'Is pregnant right now',
      'Has the same due date month',
      'Is the mom-to-be\'s sister',
      'Is a work colleague',
      'Has been through morning sickness',
      'Is planning to have kids soon',
      'Has children of the same gender',
      'Has gone through labor naturally',
      'Is a labor and delivery nurse',
      'Has had a C-section',
      'Is a pediatrician or works with kids',
      'Has breastfed for over a year',
      'Has used cloth diapers',
      'Has had a home birth',
      'Is a stay-at-home parent',
      'Has used a midwife',
      'Has had children 10+ years apart',
      'Is a stepparent',
      'Has had a baby in the same hospital',
      'Has children born in different states',
      'Has been pregnant during a major holiday',
      'Has had a baby during a pandemic',
      'Has the same baby name picked out',
      'Has experience with postpartum depression',
      'Has had a baby in summer',
      'Has used a doula',
      'Has children who are teenagers',
      'Has had a baby shower for each child',
      'Has hand-me-downs to share',
      'Has used the same pediatrician',
      'Has had a gender reveal party',
      'Has experience with sleep training',
      'Has nursed in public'
    ],
    'travel-experiences': [
      'Has been to all 50 states',
      'Has traveled to another continent',
      'Has been on a cruise',
      'Has stayed in a hostel',
      'Has been backpacking',
      'Has missed a flight',
      'Has been on a road trip longer than 1000 miles',
      'Has traveled solo',
      'Has been to a music festival abroad',
      'Has experienced jet lag',
      'Has been camping in another country',
      'Has taken a train across a country',
      'Has been to a UNESCO World Heritage site',
      'Has tried exotic food while traveling',
      'Has gotten lost in a foreign city',
      'Has learned basic phrases in another language',
      'Has been to a beach in 3+ countries',
      'Has taken a helicopter or small plane',
      'Has stayed with locals (Airbnb/Couchsurfing)',
      'Has been on a safari',
      'Has visited ancient ruins',
      'Has been to a famous landmark',
      'Has experienced culture shock',
      'Has been to a foreign wedding',
      'Has traveled for work',
      'Has been to a monastery or temple',
      'Has taken a cooking class abroad',
      'Has been on a spontaneous trip',
      'Has missed luggage on a trip',
      'Has been to a country where they don\'t speak the language',
      'Has been to a natural wonder',
      'Has traveled during a holiday abroad',
      'Has been to a foreign grocery store',
      'Has taken public transportation in another country',
      'Has been to a foreign hospital',
      'Has experienced a natural phenomenon while traveling',
      'Has been to more than 5 countries',
      'Has lived abroad for 3+ months',
      'Has been to a foreign sporting event',
      'Has gotten a stamp in their passport this year'
    ],
    'food-adventures': [
      'Has tried sushi',
      'Has eaten insects intentionally',
      'Has been to a Michelin-starred restaurant',
      'Has tried durian fruit',
      'Has eaten something they couldn\'t identify',
      'Has been food poisoned abroad',
      'Has tried escargot',
      'Has eaten street food in Asia',
      'Has tried haggis',
      'Has been to a wine tasting',
      'Has tried fermented shark',
      'Has eaten at a food truck',
      'Has tried balut (duck embryo)',
      'Has been to a farmers market abroad',
      'Has tried century eggs',
      'Has eaten something still moving',
      'Has tried blood sausage',
      'Has been to a cooking class',
      'Has tried Rocky Mountain oysters',
      'Has eaten spicy food and cried',
      'Has tried sea urchin',
      'Has been to a foreign McDonald\'s',
      'Has tried tripe',
      'Has eaten with their hands traditionally',
      'Has tried fermented fish sauce',
      'Has been to a night market',
      'Has tried casu marzu (maggot cheese)',
      'Has eaten a whole fish (with head)',
      'Has tried bird\'s nest soup',
      'Has been to a brewery tour',
      'Has tried geoduck clam',
      'Has eaten something pickled and unusual',
      'Has tried yak meat',
      'Has been to a food festival',
      'Has tried fermented horse milk',
      'Has eaten cactus',
      'Has tried chicken feet',
      'Has been to a chocolate factory',
      'Has tried ant larvae',
      'Has eaten something flambéed'
    ],
    'holiday-traditions': [
      'Always decorates before Thanksgiving',
      'Has an advent calendar tradition',
      'Makes the same cookies every year',
      'Has a special holiday movie tradition',
      'Opens one present on Christmas Eve',
      'Has a New Year\'s resolution tradition',
      'Always travels for the holidays',
      'Has a special holiday meal tradition',
      'Has holiday pajama tradition',
      'Makes homemade gifts',
      'Has a special ornament collection',
      'Goes to midnight mass or service',
      'Has a holiday card photo tradition',
      'Always volunteers during holidays',
      'Has a special holiday drink recipe',
      'Leaves cookies for Santa',
      'Has a birthday close to Christmas',
      'Has a special Thanksgiving tradition',
      'Celebrates a different cultural holiday',
      'Has an ugly sweater collection',
      'Always watches the same holiday specials',
      'Has a special New Year\'s Eve tradition',
      'Celebrates with extended family',
      'Has a holiday light display tradition',
      'Makes the same holiday breakfast',
      'Has a special gift-wrapping style',
      'Celebrates multiple religious holidays',
      'Has a special holiday game tradition',
      'Always donates during the holidays',
      'Has a holiday concert tradition',
      'Celebrates Boxing Day',
      'Has a special holiday candle ritual',
      'Always hosts holiday parties',
      'Has a special holiday story tradition',
      'Celebrates with friends instead of family',
      'Has a holiday countdown tradition',
      'Always shops early for holidays',
      'Has a special holiday music playlist',
      'Celebrates holidays differently each year',
      'Has been to Times Square for New Year\'s'
    ],
    'workout-fitness': [
      'Has run a 5K',
      'Has tried yoga',
      'Has lifted weights',
      'Has done a fitness challenge',
      'Has tried CrossFit',
      'Has been to a spin class',
      'Has tried Pilates',
      'Has done a workout video at home',
      'Has tried rock climbing',
      'Has been swimming for exercise',
      'Has tried kickboxing',
      'Has done a plank for over a minute',
      'Has tried barre classes',
      'Has been hiking',
      'Has tried martial arts',
      'Has done burpees (and survived)',
      'Has tried Zumba or dance fitness',
      'Has used a fitness tracker',
      'Has tried outdoor bootcamp',
      'Has been to a gym',
      'Has tried circuit training',
      'Has done squats until failure',
      'Has tried hot yoga',
      'Has been cycling outdoors',
      'Has tried resistance band workouts',
      'Has done push-ups',
      'Has tried HIIT workouts',
      'Has been to a fitness retreat',
      'Has tried aqua aerobics',
      'Has done lunges',
      'Has tried meditation',
      'Has been running outdoors',
      'Has tried kettlebell exercises',
      'Has done sit-ups',
      'Has tried suspension training (TRX)',
      'Has been to a fitness class with friends',
      'Has tried bodyweight exercises',
      'Has done mountain climbers',
      'Has tried foam rolling',
      'Has set a fitness goal this year'
    ],
    'college-life': [
      'Has lived in a dorm',
      'Has pulled an all-nighter studying',
      'Has changed majors',
      'Has joined a fraternity or sorority',
      'Has been to a college party',
      'Has eaten ramen noodles for multiple meals',
      'Has fallen asleep in a lecture',
      'Has done laundry at 2 AM',
      'Has had a roommate conflict',
      'Has participated in spring break',
      'Has been to office hours',
      'Has worked a campus job',
      'Has been in a study group',
      'Has cramped for finals',
      'Has been to a football game',
      'Has lived off campus',
      'Has taken a class pass/fail',
      'Has been to the library at midnight',
      'Has had a meal plan',
      'Has been homesick',
      'Has procrastinated on a major assignment',
      'Has been to a professor\'s house',
      'Has participated in homecoming',
      'Has been in a college club',
      'Has studied abroad',
      'Has had a long-distance relationship',
      'Has skipped class to sleep in',
      'Has been to a college formal',
      'Has lived with more than 2 roommates',
      'Has been to graduation',
      'Has taken a summer class',
      'Has been to campus health center',
      'Has participated in intramural sports',
      'Has been to a poetry reading or open mic',
      'Has done an internship',
      'Has been to career services',
      'Has attended a college play or concert',
      'Has been in honors program',
      'Has written for college newspaper',
      'Has graduated with student loan debt'
    ],
    'numbers': Array.from({length: 100}, (_, i) => (i + 1).toString()),
    'books-2025': [
      'Flesh',
      'James',
      'The True True Story of Raja the Gullible (and His Mother)',
      'The Safekeep',
      'The Story of a Heart',
      'One Day, Everyone Will Have Always Been Against This',
      'Native Nations',
      'Onyx Storm',
      'Sunrise on the Reaping',
      'Great Big Beautiful Life',
      'Alchemised',
      'Atmosphere',
      'The Secret of Secrets',
      'Say You\'ll Remember Me',
      'We Do Not Part',
      'The Widow',
      'The Crash',
      'Beautiful Ugly',
      'The Black Wolf',
      'The God of the Woods',
      'The Intruder',
      'Remain',
      'Stone Yard Devotional',
      'Deep End',
      'The Women',
      'Dream Count',
      'The Wedding People',
      'Funny Story',
      'Playground',
      'Intermezzo',
      'A Curse Carved in Bone',
      'The Buffalo Hunter Hunter',
      'Empire of the Dawn',
      'Witchcraft for Wayward Girls',
      'Wind and Truth',
      'Apprentice to the Villain',
      'Somewhere Beyond the Sea',
      'Everything Is Tuberculosis',
      'The Look',
      'Abundance',
      'Mark Twain',
      'Shot Ready',
      'The Anxious Generation',
      'The Idaho Four',
      'Didion and Babitz',
      'Every Living Thing',
      'Lovely One',
      'Knife',
      'Nexus',
      'War'
    ],
    'movies-2025-new': [
      'One Battle After Another',
      'Frankenstein',
      'Die, My Love',
      'Marty Supreme',
      'Hamnet',
      'Jay Kelly',
      'Presence',
      'Black Bag',
      'The Conjuring: Last Rites',
      'Predator: Badlands',
      'Zootopia 2',
      'How to Train Your Dragon',
      'Fantastic Four: First Steps',
      'Thunderbolts',
      'Captain America: Brave New World',
      'Now You See Me: Now You Don\'t',
      'The Naked Gun',
      'Snow White',
      'Tron: Ares',
      'F1',
      'Sinners',
      'Weapons',
      'Wicked: For Good',
      'A Minecraft Movie',
      'Jurassic World Rebirth',
      'Sorry, Baby',
      'Sentimental Value',
      'KPOP Demon Hunters',
      'Bugonia',
      'Wake Up Dead Man: A Knives Out Mystery',
      'One of Them Days',
      'Paddington in Peru',
      'If I had Legs, I\'d Kick you',
      '28 Years Later',
      'Together',
      'The Testament of Ann Lee',
      'The Long Walk',
      'The Running Man',
      'Caught Stealing',
      'Superman',
      'Mission: Impossible - The Final Reckoning',
      'Materialists',
      'The Phoenician Scheme'
    ],
    'resolutions-2025': [
      'Save more money',
      'Improve physical health',
      'Exercise more',
      'Eat healthier',
      'Lose weight',
      'Improve mental health',
      'Get finances in order',
      'Learn a new skill',
      'Read more books',
      'Improve personal relationships',
      'Spend more time with family',
      'Make new friends',
      'Travel more',
      'Learn a new hobby',
      'Meditate regularly',
      'Be more mindful',
      'Reduce stress',
      'Stop smoking',
      'Drink less alcohol',
      'Stop gossiping',
      'Be kind on social media',
      'Stop multitasking',
      'Talk less, listen more',
      'Give one compliment a day',
      'Drink more water',
      'Sleep better',
      'Stretch more',
      'Manage stress through meditation',
      'Take vitamins regularly',
      'Go to dentist appointments',
      'Clean regularly',
      'Declutter personal space',
      'Create a budget',
      'Pay off debt',
      'Invest more money',
      'Don\'t buy unnecessary things',
      'Call friends instead of texting',
      'Strengthen family bonds',
      'Pay it forward',
      'Do volunteer work',
      'Cook more',
      'Take a haircut',
      'Craft something DIY',
      'Start a journal',
      'Do something that scares you',
      'Go somewhere you\'ve never been',
      'Improve work performance',
      'Focus more on career goals',
      'Find work-life balance'
    ],
    'trends-2025': [
      'Wore animal print',
      'Watched Wicked: For Good',
      'Watched K-pop Demon Hunters on Netflix',
      'Watched Kendrick Lamar\'s Super Bowl halftime performance',
      'Watched Severance',
      'Talked about Taylor Swift\'s The Life of a Showgirl album',
      'Consumed matcha',
      'Used Beef Tallow',
      'Shaved head',
      'Grew a Mustache',
      'Wore something inspired by a celebrity',
      'Wore a Halloween Costume influenced by 2025 pop culture',
      'Joined a Run Club',
      'Attended or watched Love Island',
      'Watched Robert Irwin or Alix Earle on Dancing with the Stars',
      'Attended a music festival',
      'Saw Jeff Bezos and Lauren Sánchez\'s Venice wedding',
      'Watched Katy Perry\'s space voyage',
      'Tried alternative therapy',
      'Tracked fitness with wearable technology',
      'Used ClassPass',
      'Listened to Life of a Showgirl',
      'Saw a show at the Spheres',
      'Took a digital detox or phone-free weekend',
      'Overwhelmed by AI Slop',
      'Raw-dogged a Flight',
      'Found a Third Place in 2025',
      'Ran a marathon or half-marathon',
      'Bleached eyebrows',
      'Adopted a -core aesthetic',
      'Bought Smart/AI Glasses',
      'Discussed Sydney Sweeney',
      'Drank or made a mocktail',
      'Used words: Crash out, Brain rot, cooked, aura points',
      'Watched The White Lotus Season 3',
      'Bought or Played a Switch 2',
      'Read Onyx Storm',
      'Vacationed in Japan',
      'Tried Mouth Taping',
      'Watched an F1 Race'
    ],
    'tv-shows-2025': [
      'Andor',
      'The Studio',
      'Adolescence',
      'Shōgun',
      'Baby Reindeer',
      'Hacks',
      'The Bear',
      'Slow Horses',
      'The Penguin',
      'Stranger Things 5',
      'Squid Game',
      'The Last of Us',
      'The White Lotus: Thailand',
      'Wednesday',
      'Severance',
      'Alien: Earth',
      'Daredevil: Born Again',
      'Bluey',
      'Love Is Blind',
      'Ironheart',
      'Tracker',
      'Matlock',
      'High Potential',
      'NCIS: Origins',
      'Georgie & Mandy\'s First Marriage',
      'Ghosts',
      'Chicago Fire',
      'Abbott Elementary',
      'Dancing With the Stars',
      '9-1-1',
      'Poker Face',
      'Black Mirror',
      'Presumed Innocent',
      'Monsters: The Lyle and Erik Menendez Story',
      'All Her Fault',
      'Sherlock & Daughter',
      'Watson',
      'The Day of the Jackal',
      'The Pitt',
      'Pluribus',
      'The Beast in Me',
      'Gen V',
      'The Summer I Turned Pretty'
    ],
    'christmas-bucketlist': [
      'Decorated the Christmas Tree',
      'Made a Gingerbread House',
      'Baked Christmas Cookies',
      'Created Personalized Ornaments',
      'Made DIY Snow Globes',
      'Designed Paper Snowflakes',
      'Crafted Handprint Reindeer',
      'Made a Christmas Wreath',
      'Painted Holiday Ornaments',
      'Set Up a Christmas Photo Booth',
      'Set Up a Hot Chocolate Bar',
      'Hosted a Paint and Sip',
      'Created Holiday Treats',
      'Planned a Special Christmas Breakfast',
      'Went Sledding',
      'Built a Snowman',
      'Took an Ice Skating Trip',
      'Went Christmas Light Viewing',
      'Visited a Christmas Tree Farm',
      'Took a Family Walk or Hike',
      'Enjoyed a Horse-Drawn Carriage Ride',
      'Hosted a Christmas Movie Marathon',
      'Played Holiday Board Games',
      'Created a Christmas Playlist and Danced',
      'Hosted a Game Night',
      'Wrote Letters to Santa',
      'Made Handmade Christmas Cards',
      'Wrote Thank You Cards',
      'Went Christmas Caroling',
      'Read Classic Christmas Stories'
    ],
    'deep-questions': [
      'Which celebrity drama do you follow most closely?',
      'What\'s the best book you\'ve read in the last 5 years?',
      'What movie did you love most when you were in middle school?',
      'What topic could you talk about for 20 minutes without preparation?',
      'What\'s the worst gift someone has ever given you?',
      'What\'s a rule from your childhood that seems ridiculous or funny now?',
      'If you had to give aliens three gifts representing humanity, what would they be?',
      'When did you last use glitter?',
      'When did you last blow up a balloon using just your mouth?',
      'What\'s your favorite building in your community and how did it become your favorite?',
      'Did you watch Spongebob growing up?',
      'Do you have a theory about how you\'ll die?',
      'What recently made you laugh out loud?',
      'Which grocery store do you prefer shopping at?',
      'What brings whimsy into your daily life?',
      'Which TikTok or viral trend really caught your attention?',
      'If you had to spend $1000 in one hour, what would you do?',
      'Have you ever tried birding?',
      'Do you enjoy visiting museums?',
      'What\'s your go-to cocktail?',
      'If you could live in any fantasy world, which would you choose?',
      'Are you into fancy desk setups?',
      'Do you care about wire management?',
      'What moment brought you the most joy when giving someone a gift?',
      'Do you enjoy hosting events?',
      'What\'s the best dish you\'ve ever cooked?',
      'What\'s something that really challenged you this year?',
      'What\'s a quote that resonates with you?',
      'Are you someone who avoids taking risks?',
      'How did you first meet your closest friend?',
      'What\'s a small thing that never fails to brighten your day?',
      'What\'s something visible from your desk, wall, or window that always lifts your spirits?',
      'Do you have people you look up to or consider mentors?',
      'If you could choose an animal sidekick, what would it be and why?',
      'What emoji do you use most frequently on your phone?',
      'Do you have a favorite dinosaur?',
      'Have you picked up any useful tips recently?',
      'What\'s the best article you\'ve read lately?',
      'What\'s one thing about your job you wish could be automated?',
      'If you had to pick a color that describes your personality today, what would it be?',
      'What\'s your best life hack?',
      'If you had a fully paid year off from work, what would you do?',
      'If you were a season, which would you be: winter, spring, summer, or autumn?',
      'Would you prefer a three-week trip to multiple destinations or just one place?',
      'What was the first concert or live show you ever went to?',
      'What\'s one item you always pack when traveling?',
      'Have you ever overcome a fear that used to hold you back?',
      'Which popular hobby do you think is overrated?',
      'What\'s a new habit or practice you\'re working on developing?',
      'How do you like to learn new things?',
      'What\'s an adult problem you feel completely unprepared for?'
    ],
    'family-gathering': [
      'What\'s your favorite holiday food, and what\'s your least favorite?',
      'What song has been stuck in your head lately?',
      'What makes you laugh the most?',
      'If you could have any superpower, what would it be?',
      'What\'s your favorite animal, and why?',
      'If you could visit any place in the world, where would you go?',
      'What\'s a funny joke or riddle you know?',
      'What\'s your favorite holiday memory from childhood?',
      'Which memory from past holidays do you think about the most?',
      'What\'s the best holiday present you\'ve ever received?',
      'What\'s your family\'s funniest holiday story?',
      'What was the nicest thing someone has ever done for you?',
      'If you could have dinner with any famous person, who would it be?',
      'Do you prefer decorating before or after Thanksgiving?',
      'Do you go for a real tree or an artificial one?',
      'What\'s your stance on matching holiday pajamas: charming or never?',
      'What\'s one holiday tradition you\'d love to start or stop, and why?',
      'What\'s your favorite low-effort holiday ritual?',
      'Which holiday scent instantly feels like home to you?',
      'What\'s something you\'ve learned this past year that changed you for the better?',
      'What\'s one thing you\'re grateful for this year that surprises you?',
      'What area did you grow in this year?',
      'Did anything unexpected happen that you\'re thankful for?',
      'Who or what has made your year a little brighter?',
      'What does "home" mean to you right now?',
      'What\'s one way you\'d like to show more kindness in the new year?',
      'What would you want to teach someone if you had to?',
      'What\'s your biggest goal for the upcoming year?',
      'If you could change one thing about this year, what would it be?',
      'What\'s something you want to learn how to do in the upcoming year?'
    ],
    'indoor-winter-adult': [
      'Attended a Paint and Sip',
      'Took Pottery Classes',
      'Created Ceramics',
      'Took Glass Blowing Classes',
      'Took Woodworking Classes',
      'Painted on Canvas',
      'Made DIY Candles',
      'Painted Figurines',
      'Attended a Live Comedy Show',
      'Took Online Mixology Classes',
      'Attended a Wine and Cheese Tasting',
      'Hosted a Dinner Party',
      'Went to Karaoke Night',
      'Watched a Themed Movie Marathon',
      'Went to a Jazz Club',
      'Attended Theater or Ballet',
      'Did Escape Room Challenges',
      'Did Virtual Escape Rooms',
      'Played Online Trivia Games',
      'Played in a Board Game Tournament',
      'Played Darts',
      'Played Indoor Bocce',
      'Played Video Games',
      'Did Slot Car Racing',
      'Took Couples Yoga or Meditation Class',
      'Went Indoor Rock Climbing',
      'Did Gym Fitness Routine',
      'Took Dance Classes',
      'Took Culinary Classes',
      'Attended Book Club with Discussions'
    ],
    'indoor-winter-family': [
      'Watched a Movie Marathon',
      'Played in a Board Games Tournament',
      'Did a Puzzle Challenge',
      'Did DIY Karaoke Night',
      'Went Bowling',
      'Played Indoor Hide-and-Seek',
      'Played Balloon Volleyball',
      'Did an Indoor Obstacle Course',
      'Baked Christmas Cookies',
      'Made a Gingerbread House',
      'Prepared Snowman Pancakes',
      'Made a Hot Chocolate Bar',
      'Baked a Mug Cake',
      'Made Rock Candy',
      'Made DIY Snow Globes',
      'Designed Paper Snowflakes',
      'Painted Holiday Ornaments',
      'Made Homemade Playdough',
      'Created a Winter Sensory Bin',
      'Designed Friendship Bracelets',
      'Made Duct Tape Crafts',
      'Built with Lego or Building Blocks',
      'Built a Blanket Fort',
      'Had an Indoor Snowball Fight',
      'Created an Indoor Picnic',
      'Had a Dance Party',
      'Played Balloon Tennis',
      'Built Structures with Pillows',
      'Learned a New Skill Together',
      'Recorded Family Stories'
    ],
    'outdoor-winter': [],
    'outdoor-winter-adult': [
      'Went Downhill Skiing',
      'Went Snowboarding',
      'Went Cross-Country Skiing',
      'Went Snowshoeing',
      'Went Backcountry Ski Touring',
      'Went Helicopter Skiing',
      'Went Skate Skiing',
      'Went Fat Tire Biking',
      'Went Ice Climbing',
      'Traversed a Glacier',
      'Went Snowmobiling',
      'Went Dog Sledding',
      'Did a Polar Bear Swim',
      'Went Mountaineering',
      'Went Ice Fishing',
      'Went Winter Surfing',
      'Went Stand-Up Paddle Boarding',
      'Went Hang Gliding',
      'Went Winter Trail Running',
      'Did Outdoor Workouts',
      'Went Ice Skating',
      'Went Horseback Riding',
      'Went on Long-Distance Dog Walks',
      'Jumped Rope Outside',
      'Witnessed the Northern Lights',
      'Stayed at an Ice Hotel',
      'Did Winter Photography',
      'Went on a Hot Springs Road Trip',
      'Went Winter Glamping or Stayed in a Cozy Cabin',
      'Explored Backcountry Wilderness'
    ],
    'outdoor-winter-family': [
      'Built a Snowman',
      'Had a Snowball Fight',
      'Went Sledding or Tubing',
      'Made Snow Angels',
      'Went Ice Skating',
      'Built Snow Forts',
      'Went Cross-Country Skiing',
      'Went Snowshoeing',
      'Went Snowmobiling',
      'Made Frozen Bubbles',
      'Took a Winter Hike',
      'Did a Winter Scavenger Hunt',
      'Painted with Snow',
      'Searched for Animal Tracks',
      'Built a Nest Challenge',
      'Made a Bird Feeder',
      'Visited a Winter Festival or Market',
      'Admired Holiday Lights and Decor',
      'Flew a Kite',
      'Went to the Beach',
      'Played Snow Golf',
      'Played Dodgeball with Snowballs',
      'Played Pin-the-Nose-on-Snowman',
      'Built a Snow Volcano',
      'Played Winter Playground Games',
      'Played Street Hockey',
      'Built an Outdoor Obstacle Course',
      'Had a Winter Picnic',
      'Built a Bonfire',
      'Explored a Historic Village'
    ],
    'thanksgiving': [
      'Brought a dish to share',
      'Made homemade pie this year',
      'Loves mashed potatoes more than turkey',
      'Can\'t cook without a recipe',
      'Burnt something in the kitchen this year',
      'Had seconds of stuffing',
      'Tried a new Thanksgiving recipe',
      'Watched the Thanksgiving Day parade',
      'Napped after dinner',
      'Watched football during Thanksgiving',
      'Said grace or gave a toast',
      'Carved the turkey',
      'Set the table',
      'Helped with cleanup',
      'Told a joke at the table',
      'Wore stretchy pants',
      'Asked for a recipe',
      'Made someone laugh today',
      'Visited from out of town',
      'Tried to avoid politics at dinner',
      'Has been to more than 5 Thanksgiving dinners',
      'Is having their first Thanksgiving',
      'Said "I\'m grateful for..."',
      'Wore fall colors',
      'Decorated with pumpkins or gourds',
      'Brought a plus-one',
      'Made a Thanksgiving playlist',
      'Is seeing family after a long time',
      'Can fit more on their plate than anyone',
      'Left the table to take a nap'
    ],
    'ultra-specific-resolutions': [
      'Have weekly family game night',
      'Do one random act of kindness per week',
      'Volunteer 4 hours per month',
      'Cook at home 4 times per week',
      'Get a new haircut',
      'Complete a DIY project',
      'Write in journal 3 times per week',
      'Try one new activity that scares you',
      'Visit a place you\'ve never been',
      'Complete a work certification course',
      'Set 3 specific career goals',
      'Take one full day off per week',
      'Drink 8 glasses of water daily',
      'Go to bed by 10 PM',
      'Stretch for 10 minutes daily',
      'Practice yoga weekly',
      'Take vitamins daily',
      'Go to dentist twice this year',
      'Declutter one room per month',
      'Do a 15-minute daily tidy',
      'Donate 10 items per month',
      'Create and stick to a monthly budget',
      'Pay off credit card debt',
      'Invest 10% of income',
      'Wait 24 hours before buying non-essentials',
      'Save $100 per month',
      'Build an emergency fund',
      'Exercise 3 times per week',
      'Eat 5 servings of vegetables daily',
      'Lose 10 pounds',
      'Practice gratitude daily',
      'See a therapist monthly',
      'Track expenses for 3 months',
      'Learn to code',
      'Read 12 books this year',
      'Have weekly date nights',
      'Have family dinner 3 times per week',
      'Join a club or meetup group',
      'Visit 2 new countries',
      'Take up photography',
      'Meditate for 10 minutes daily',
      'Take a 15-minute walk daily',
      'Have 2 alcohol-free days per week'
    ],
    'winter-adult-all': [
      'Attended a Paint and Sip',
      'Took Pottery Classes',
      'Created Ceramics',
      'Took Glass Blowing Classes',
      'Took Woodworking Classes',
      'Painted on Canvas',
      'Made DIY Candles',
      'Painted Figurines',
      'Attended a Live Comedy Show',
      'Took Online Mixology Classes',
      'Attended a Wine and Cheese Tasting',
      'Hosted a Virtual Dinner Party',
      'Went to Karaoke Night',
      'Watched a Themed Movie Marathon',
      'Went to a Jazz Club',
      'Attended Theater or Ballet',
      'Did Escape Room Challenges',
      'Did Virtual Escape Rooms',
      'Played Online Trivia Games',
      'Played in a Board Game Tournament',
      'Played Darts',
      'Played Indoor Bocce',
      'Played Video Games',
      'Did Slot Car Racing',
      'Took Couples Yoga or Meditation Class',
      'Went Indoor Rock Climbing',
      'Did Gym Fitness Routine',
      'Took Dance Classes',
      'Took Culinary Classes',
      'Attended Book Club with Discussions',
      'Went Downhill Skiing',
      'Went Snowboarding',
      'Went Cross-Country Skiing',
      'Went Snowshoeing',
      'Went Backcountry Ski Touring',
      'Went Helicopter Skiing',
      'Went Skate Skiing',
      'Went Fat Tire Biking',
      'Went Ice Climbing',
      'Traversed a Glacier',
      'Went Snowmobiling',
      'Went Dog Sledding',
      'Did a Polar Bear Swim',
      'Went Mountaineering',
      'Went Ice Fishing',
      'Went Winter Surfing',
      'Went Stand-Up Paddle Boarding',
      'Went Hang Gliding',
      'Went Winter Trail Running',
      'Did Outdoor Workouts',
      'Went Ice Skating',
      'Went Horseback Riding',
      'Went on Long-Distance Dog Walks',
      'Jumped Rope Outside',
      'Witnessed the Northern Lights',
      'Stayed at an Ice Hotel',
      'Did Winter Photography',
      'Went on a Hot Springs Road Trip',
      'Went Winter Glamping or Stayed in a Cozy Cabin',
      'Explored Backcountry Wilderness'
    ],
    'winter-family-all': [
      'Watched a Movie Marathon',
      'Played in a Board Games Tournament',
      'Did a Puzzle Challenge',
      'Did DIY Karaoke Night',
      'Went Bowling',
      'Played Indoor Hide-and-Seek',
      'Played Balloon Volleyball',
      'Did an Indoor Obstacle Course',
      'Baked Christmas Cookies',
      'Made a Gingerbread House',
      'Prepared Snowman Pancakes',
      'Made a Hot Chocolate Bar',
      'Baked a Mug Cake',
      'Made Rock Candy',
      'Made DIY Snow Globes',
      'Designed Paper Snowflakes',
      'Painted Holiday Ornaments',
      'Made Homemade Playdough',
      'Created a Winter Sensory Bin',
      'Designed Friendship Bracelets',
      'Made Duct Tape Crafts',
      'Built with Lego or Building Blocks',
      'Built a Blanket Fort',
      'Had an Indoor Snowball Fight',
      'Created an Indoor Picnic',
      'Had a Dance Party',
      'Played Balloon Tennis',
      'Built Structures with Pillows',
      'Learned a New Skill Together',
      'Recorded Family Stories',
      'Built a Snowman',
      'Had a Snowball Fight',
      'Went Sledding or Tubing',
      'Made Snow Angels',
      'Went Ice Skating',
      'Built Snow Forts',
      'Went Cross-Country Skiing',
      'Went Snowshoeing',
      'Went Snowmobiling',
      'Made Frozen Bubbles',
      'Took a Winter Hike',
      'Did a Winter Scavenger Hunt',
      'Painted with Snow',
      'Searched for Animal Tracks',
      'Built a Nest Challenge',
      'Made a Bird Feeder',
      'Visited a Winter Festival or Market',
      'Admired Holiday Lights and Decor',
      'Flew a Kite',
      'Went to the Beach',
      'Played Snow Golf',
      'Played Dodgeball with Snowballs',
      'Played Pin-the-Nose-on-Snowman',
      'Built a Snow Volcano',
      'Played Winter Playground Games',
      'Played Street Hockey',
      'Built an Outdoor Obstacle Course',
      'Had a Winter Picnic',
      'Built a Bonfire',
      'Explored a Historic Village'
    ]
  };

  const parsePhrases = useCallback((input) => {
    if (!input.trim()) return [];
    
    // First try line breaks (most common and preferred)
    if (input.includes('\n')) {
      return input.split('\n')
        .map(phrase => phrase.trim())
        .filter(phrase => phrase.length > 0);
    }
    
    // Then try semicolons
    if (input.includes(';')) {
      return input.split(';')
        .map(phrase => phrase.trim())
        .filter(phrase => phrase.length > 0);
    }
    
    // Finally try commas
    if (input.includes(',')) {
      return input.split(',')
        .map(phrase => phrase.trim())
        .filter(phrase => phrase.length > 0);
    }
    
    // If no delimiters, treat as single phrase
    return [input.trim()];
  }, []);

  const handlePhraseInputChange = useCallback((value) => {
    setPhraseInput(value);
    setPhrases(parsePhrases(value));
  }, [parsePhrases]);

  const addSamplePhrases = useCallback((type = 'icebreakers') => {
    const selectedPhrases = samplePhrases[type] || samplePhrases.icebreakers;
    const sampleText = selectedPhrases.join('\n');
    setPhraseInput(sampleText);
    setPhrases(selectedPhrases);
    
    // Return the suggested title for this template
    return templateTitles[type] || 'BINGO!';
  }, []);

  const getSuggestedTitle = useCallback((type) => {
    return templateTitles[type] || 'BINGO!';
  }, []);

  const clearAll = useCallback(() => {
    setPhraseInput('');
    setPhrases([]);
  }, []);

  return {
    phraseInput,
    phrases,
    handlePhraseInputChange,
    addSamplePhrases,
    getSuggestedTitle,
    clearAll
  };
};

export default usePhraseManager;
