export const themes = [
  {
    id: 'halloween',
    name: 'Halloween',
    titleFont: 'Helvetica-Bold',
    titleColor: '#F4761F',
    cellFont: 'Helvetica',
    useGradient: true,
    gradientColor1: '#1A1523',
    gradientColor2: '#3B1E54',
    gradientColor3: null,
    backgroundColor: '#1A1523',
    borderColor: '#F4761F',
    freeSpaceBackgroundColor: '#F4761F',
    freeSpaceFontColor: '#1A1523',
    cellTextColor: '#1f2937',
    subtitleColor: '#E9D5FF',
    borderWidth: 2,
    gridBorderRadius: 6,
    cellBackgroundMode: 'white',
    cellBackgroundTint: '#f8fafc',
    gradientDirection: 'vertical',
    cardMatEnabled: false,
    backgroundPattern: null,
    backgroundPatternOpacity: 0.15
  },
  {
    id: 'christmas',
    name: 'Christmas',
    titleFont: 'Helvetica-Bold',
    titleColor: '#C8102E',
    cellFont: 'Helvetica',
    useGradient: true,
    gradientColor1: '#FFFFFF',
    gradientColor2: '#DC143C',
    gradientColor3: null,
    backgroundColor: '#FFFFFF',
    borderColor: '#C8102E',
    freeSpaceBackgroundColor: '#FFE4E1',
    freeSpaceFontColor: '#C8102E',
    cellTextColor: '#1f2937',
    subtitleColor: '#4b5563',
    borderWidth: 1.5,
    gridBorderRadius: 8,
    cellBackgroundMode: 'white',
    cellBackgroundTint: '#f8fafc',
    gradientDirection: 'vertical',
    cardMatEnabled: false,
    backgroundPattern: null,
    backgroundPatternOpacity: 0.15
  },
  {
    id: 'thanksgiving',
    name: 'Thanksgiving',
    titleFont: 'Helvetica-Bold',
    titleColor: '#8B4513',
    cellFont: 'Helvetica',
    useGradient: true,
    gradientColor1: '#FFF8DC',
    gradientColor2: '#FF8C00',
    gradientColor3: null,
    backgroundColor: '#FFF8DC',
    borderColor: '#8B4513',
    freeSpaceBackgroundColor: '#FFE4B5',
    freeSpaceFontColor: '#8B4513',
    cellTextColor: '#1f2937',
    subtitleColor: '#4b5563',
    borderWidth: 1.5,
    gridBorderRadius: 8,
    cellBackgroundMode: 'white',
    cellBackgroundTint: '#f8fafc',
    gradientDirection: 'vertical',
    cardMatEnabled: false,
    backgroundPattern: null,
    backgroundPatternOpacity: 0.15
  },
  {
    id: 'school',
    name: 'School',
    titleFont: 'Helvetica-Bold',
    titleColor: '#1E3A8A',
    cellFont: 'Times-Roman',
    useGradient: true,
    gradientColor1: '#FFFFFF',
    gradientColor2: '#FCD34D',
    gradientColor3: null,
    backgroundColor: '#FFFFFF',
    borderColor: '#1E3A8A',
    freeSpaceBackgroundColor: '#DBEAFE',
    freeSpaceFontColor: '#1E3A8A',
    cellTextColor: '#1f2937',
    subtitleColor: '#4b5563',
    borderWidth: 1.5,
    gridBorderRadius: 8,
    cellBackgroundMode: 'white',
    cellBackgroundTint: '#f8fafc',
    gradientDirection: 'vertical',
    cardMatEnabled: false,
    backgroundPattern: null,
    backgroundPatternOpacity: 0.15
  },
  {
    id: 'princess',
    name: 'Princess',
    titleFont: 'Helvetica-Bold',
    titleColor: '#C71585',
    cellFont: 'Helvetica',
    useGradient: true,
    gradientColor1: '#FFE4E1',
    gradientColor2: '#DA70D6',
    gradientColor3: null,
    backgroundColor: '#FFE4E1',
    borderColor: '#C71585',
    freeSpaceBackgroundColor: '#FCE7F3',
    freeSpaceFontColor: '#C71585',
    cellTextColor: '#1f2937',
    subtitleColor: '#4b5563',
    borderWidth: 1.5,
    gridBorderRadius: 8,
    cellBackgroundMode: 'white',
    cellBackgroundTint: '#f8fafc',
    gradientDirection: 'vertical',
    cardMatEnabled: false,
    backgroundPattern: null,
    backgroundPatternOpacity: 0.15
  },
  {
    id: 'snowflake',
    name: 'Snowflake',
    titleFont: 'Helvetica-Bold',
    titleColor: '#4682B4',
    cellFont: 'Helvetica',
    useGradient: true,
    gradientColor1: '#F0F8FF',
    gradientColor2: '#87CEEB',
    gradientColor3: null,
    backgroundColor: '#F0F8FF',
    borderColor: '#4682B4',
    freeSpaceBackgroundColor: '#E0F6FF',
    freeSpaceFontColor: '#4682B4',
    cellTextColor: '#1f2937',
    subtitleColor: '#4b5563',
    borderWidth: 1.5,
    gridBorderRadius: 8,
    cellBackgroundMode: 'white',
    cellBackgroundTint: '#f8fafc',
    gradientDirection: 'vertical',
    cardMatEnabled: false,
    backgroundPattern: null,
    backgroundPatternOpacity: 0.15
  },
  {
    id: 'hearts',
    name: 'Hearts',
    titleFont: 'Helvetica-Bold',
    titleColor: '#DC143C',
    cellFont: 'Helvetica',
    useGradient: true,
    gradientColor1: '#FFB6C1',
    gradientColor2: '#FF69B4',
    gradientColor3: null,
    backgroundColor: '#FFB6C1',
    borderColor: '#DC143C',
    freeSpaceBackgroundColor: '#FFE4E1',
    freeSpaceFontColor: '#DC143C',
    cellTextColor: '#1f2937',
    subtitleColor: '#4b5563',
    borderWidth: 1.5,
    gridBorderRadius: 8,
    cellBackgroundMode: 'white',
    cellBackgroundTint: '#f8fafc',
    gradientDirection: 'vertical',
    cardMatEnabled: false,
    backgroundPattern: null,
    backgroundPatternOpacity: 0.15
  },
  {
    id: 'ocean',
    name: 'Ocean',
    titleFont: 'Helvetica-Bold',
    titleColor: '#000080',
    cellFont: 'Helvetica',
    useGradient: true,
    gradientColor1: '#E0F6FF',
    gradientColor2: '#00CED1',
    gradientColor3: null,
    backgroundColor: '#E0F6FF',
    borderColor: '#000080',
    freeSpaceBackgroundColor: '#B0E0E6',
    freeSpaceFontColor: '#000080',
    cellTextColor: '#1f2937',
    subtitleColor: '#4b5563',
    borderWidth: 1.5,
    gridBorderRadius: 8,
    cellBackgroundMode: 'white',
    cellBackgroundTint: '#f8fafc',
    gradientDirection: 'vertical',
    cardMatEnabled: false,
    backgroundPattern: null,
    backgroundPatternOpacity: 0.15
  },
  {
    id: 'sunset',
    name: 'Sunset',
    titleFont: 'Helvetica-Bold',
    titleColor: '#FF4500',
    cellFont: 'Helvetica',
    useGradient: true,
    gradientColor1: '#FFE4B5',
    gradientColor2: '#FF6347',
    gradientColor3: null,
    backgroundColor: '#FFE4B5',
    borderColor: '#FF4500',
    freeSpaceBackgroundColor: '#FFDAB9',
    freeSpaceFontColor: '#FF4500',
    cellTextColor: '#1f2937',
    subtitleColor: '#4b5563',
    borderWidth: 1.5,
    gridBorderRadius: 8,
    cellBackgroundMode: 'white',
    cellBackgroundTint: '#f8fafc',
    gradientDirection: 'vertical',
    cardMatEnabled: false,
    backgroundPattern: null,
    backgroundPatternOpacity: 0.15
  },
  {
    id: 'forest',
    name: 'Forest',
    titleFont: 'Helvetica-Bold',
    titleColor: '#228B22',
    cellFont: 'Helvetica',
    useGradient: true,
    gradientColor1: '#F0FFF0',
    gradientColor2: '#8FBC8F',
    gradientColor3: null,
    backgroundColor: '#F0FFF0',
    borderColor: '#228B22',
    freeSpaceBackgroundColor: '#D4EDDA',
    freeSpaceFontColor: '#228B22',
    cellTextColor: '#1f2937',
    subtitleColor: '#4b5563',
    borderWidth: 1.5,
    gridBorderRadius: 8,
    cellBackgroundMode: 'white',
    cellBackgroundTint: '#f8fafc',
    gradientDirection: 'vertical',
    cardMatEnabled: false,
    backgroundPattern: null,
    backgroundPatternOpacity: 0.15
  },
  {
    id: 'aurora',
    name: 'Aurora',
    titleFont: 'Helvetica-Bold',
    titleColor: '#0F766E',
    cellFont: 'Helvetica',
    useGradient: true,
    gradientColor1: '#ECFDF5',
    gradientColor2: '#0D9488',
    gradientColor3: '#1E3A8A',
    backgroundColor: '#ECFDF5',
    borderColor: '#0F766E',
    freeSpaceBackgroundColor: '#CCFBF1',
    freeSpaceFontColor: '#0F766E',
    cellTextColor: '#111827',
    subtitleColor: '#374151',
    borderWidth: 1.5,
    gridBorderRadius: 8,
    cellBackgroundMode: 'softTint',
    cellBackgroundTint: '#F0FDF4',
    gradientDirection: 'vertical',
    cardMatEnabled: true,
    backgroundPattern: null,
    backgroundPatternOpacity: 0.15
  },
  {
    id: 'matcha',
    name: 'Matcha sage',
    titleFont: 'Helvetica-Bold',
    titleColor: '#3F6212',
    cellFont: 'Helvetica',
    useGradient: true,
    gradientColor1: '#F7FEE7',
    gradientColor2: '#A3E635',
    gradientColor3: null,
    backgroundColor: '#F7FEE7',
    borderColor: '#3F6212',
    freeSpaceBackgroundColor: '#ECFCCB',
    freeSpaceFontColor: '#3F6212',
    cellTextColor: '#1F2937',
    subtitleColor: '#4b5563',
    borderWidth: 1.5,
    gridBorderRadius: 6,
    cellBackgroundMode: 'alternating',
    cellBackgroundTint: '#F4FBF0',
    gradientDirection: 'vertical',
    cardMatEnabled: false,
    backgroundPattern: null,
    backgroundPatternOpacity: 0.15
  },
  {
    id: 'coquette-blush',
    name: 'Coquette blush',
    titleFont: 'Helvetica-Bold',
    titleColor: '#BE185D',
    cellFont: 'Helvetica',
    useGradient: true,
    gradientColor1: '#FFF5F7',
    gradientColor2: '#FCE7F3',
    gradientColor3: '#F472B6',
    backgroundColor: '#FFF5F7',
    borderColor: '#BE185D',
    freeSpaceBackgroundColor: '#FCE7F3',
    freeSpaceFontColor: '#BE185D',
    cellTextColor: '#4D142E',
    subtitleColor: '#831843',
    borderWidth: 1.0,
    gridBorderRadius: 12,
    cellBackgroundMode: 'softTint',
    cellBackgroundTint: '#FFFDFE',
    gradientDirection: 'diagonal',
    cardMatEnabled: true,
    backgroundPattern: null,
    backgroundPatternOpacity: 0.15
  },
  {
    id: 'lavender-dream',
    name: 'Lavender dream',
    titleFont: 'Helvetica-Bold',
    titleColor: '#6D28D9',
    cellFont: 'Helvetica',
    useGradient: true,
    gradientColor1: '#FAF5FF',
    gradientColor2: '#E9D5FF',
    gradientColor3: null,
    backgroundColor: '#FAF5FF',
    borderColor: '#6D28D9',
    freeSpaceBackgroundColor: '#F3E8FF',
    freeSpaceFontColor: '#6D28D9',
    cellTextColor: '#1e1b4b',
    subtitleColor: '#4c1d95',
    borderWidth: 2.0,
    gridBorderRadius: 10,
    cellBackgroundMode: 'alternating',
    cellBackgroundTint: '#FDFBFF',
    gradientDirection: 'horizontal',
    cardMatEnabled: false,
    backgroundPattern: null,
    backgroundPatternOpacity: 0.15
  },
  {
    id: 'midnight',
    name: 'Midnight',
    titleFont: 'Helvetica-Bold',
    titleColor: '#1E293B',
    cellFont: 'Helvetica',
    useGradient: true,
    gradientColor1: '#F8FAFC',
    gradientColor2: '#94A3B8',
    gradientColor3: '#334155',
    backgroundColor: '#F8FAFC',
    borderColor: '#1E293B',
    freeSpaceBackgroundColor: '#E2E8F0',
    freeSpaceFontColor: '#1E293B',
    cellTextColor: '#0F172A',
    subtitleColor: '#334155',
    borderWidth: 2.0,
    gridBorderRadius: 8,
    cellBackgroundMode: 'white',
    cellBackgroundTint: '#f8fafc',
    gradientDirection: 'vertical',
    cardMatEnabled: true,
    backgroundPattern: null,
    backgroundPatternOpacity: 0.15
  },
  {
    id: 'citrus',
    name: 'Citrus',
    titleFont: 'Helvetica-Bold',
    titleColor: '#C2410C',
    cellFont: 'Helvetica',
    useGradient: true,
    gradientColor1: '#FFFBEB',
    gradientColor2: '#FDE047',
    gradientColor3: '#F97316',
    backgroundColor: '#FFFBEB',
    borderColor: '#C2410C',
    freeSpaceBackgroundColor: '#FEF3C7',
    freeSpaceFontColor: '#C2410C',
    cellTextColor: '#451A03',
    subtitleColor: '#7C2D12',
    borderWidth: 1.5,
    gridBorderRadius: 8,
    cellBackgroundMode: 'softTint',
    cellBackgroundTint: '#FFFEFA',
    gradientDirection: 'diagonal',
    cardMatEnabled: false,
    backgroundPattern: null,
    backgroundPatternOpacity: 0.15
  },
  {
    id: 'sage',
    name: 'Sage',
    titleFont: 'Helvetica-Bold',
    titleColor: '#2F4F4F',
    cellFont: 'Helvetica',
    useGradient: true,
    gradientColor1: '#F4F7F6',
    gradientColor2: '#C2D3CD',
    gradientColor3: null,
    backgroundColor: '#F4F7F6',
    borderColor: '#2F4F4F',
    freeSpaceBackgroundColor: '#E3ECE9',
    freeSpaceFontColor: '#2F4F4F',
    cellTextColor: '#22332F',
    subtitleColor: '#3D544F',
    borderWidth: 1.5,
    gridBorderRadius: 4,
    cellBackgroundMode: 'alternating',
    cellBackgroundTint: '#FAFCFC',
    gradientDirection: 'vertical',
    cardMatEnabled: false,
    backgroundPattern: null,
    backgroundPatternOpacity: 0.15
  },
  {
    id: 'coral',
    name: 'Coral sand',
    titleFont: 'Helvetica-Bold',
    titleColor: '#E11D48',
    cellFont: 'Helvetica',
    useGradient: true,
    gradientColor1: '#FFFBFB',
    gradientColor2: '#FFEDD5',
    gradientColor3: '#FDA4AF',
    backgroundColor: '#FFFBFB',
    borderColor: '#E11D48',
    freeSpaceBackgroundColor: '#FFE4E6',
    freeSpaceFontColor: '#E11D48',
    cellTextColor: '#4C0519',
    subtitleColor: '#880808',
    borderWidth: 1.5,
    gridBorderRadius: 10,
    cellBackgroundMode: 'softTint',
    cellBackgroundTint: '#FFFAF9',
    gradientDirection: 'diagonal',
    cardMatEnabled: true,
    backgroundPattern: null,
    backgroundPatternOpacity: 0.15
  },
  {
    id: 'slate',
    name: 'Slate industrial',
    titleFont: 'Helvetica-Bold',
    titleColor: '#0F172A',
    cellFont: 'Helvetica',
    useGradient: true,
    gradientColor1: '#F1F5F9',
    gradientColor2: '#CBD5E1',
    gradientColor3: null,
    backgroundColor: '#F1F5F9',
    borderColor: '#0F172A',
    freeSpaceBackgroundColor: '#E2E8F0',
    freeSpaceFontColor: '#0F172A',
    cellTextColor: '#1E293B',
    subtitleColor: '#475569',
    borderWidth: 2.5,
    gridBorderRadius: 0,
    cellBackgroundMode: 'alternating',
    cellBackgroundTint: '#F8FAFC',
    gradientDirection: 'horizontal',
    cardMatEnabled: false,
    backgroundPattern: null,
    backgroundPatternOpacity: 0.15
  },
  {
    id: 'golden-hour',
    name: 'Golden hour',
    titleFont: 'Helvetica-Bold',
    titleColor: '#92400E',
    cellFont: 'Helvetica',
    useGradient: true,
    gradientColor1: '#FFFDF5',
    gradientColor2: '#FDE047',
    gradientColor3: '#F59E0B',
    backgroundColor: '#FFFDF5',
    borderColor: '#92400E',
    freeSpaceBackgroundColor: '#FEF08A',
    freeSpaceFontColor: '#92400E',
    cellTextColor: '#451A03',
    subtitleColor: '#78350F',
    borderWidth: 1.5,
    gridBorderRadius: 8,
    cellBackgroundMode: 'softTint',
    cellBackgroundTint: '#FFFDF0',
    gradientDirection: 'diagonal',
    cardMatEnabled: true,
    backgroundPattern: null,
    backgroundPatternOpacity: 0.15
  },
  {
    id: 'berry',
    name: 'Vibrant Berry',
    titleFont: 'Helvetica-Bold',
    titleColor: '#86198F',
    cellFont: 'Helvetica',
    useGradient: true,
    gradientColor1: '#FDF4FF',
    gradientColor2: '#E879F9',
    gradientColor3: '#6B21A8',
    backgroundColor: '#FDF4FF',
    borderColor: '#86198F',
    freeSpaceBackgroundColor: '#FAE8FF',
    freeSpaceFontColor: '#86198F',
    cellTextColor: '#3B0764',
    subtitleColor: '#701A75',
    borderWidth: 1.5,
    gridBorderRadius: 8,
    cellBackgroundMode: 'alternating',
    cellBackgroundTint: '#FCF5FE',
    gradientDirection: 'diagonal',
    cardMatEnabled: false,
    backgroundPattern: null,
    backgroundPatternOpacity: 0.15
  },
  {
    id: 'rainbow-soft',
    name: 'Pastel Rainbow',
    titleFont: 'Helvetica-Bold',
    titleColor: '#4338CA',
    cellFont: 'Helvetica',
    useGradient: true,
    gradientColor1: '#EEF2FF',
    gradientColor2: '#E0F2FE',
    gradientColor3: '#FCE7F3',
    backgroundColor: '#EEF2FF',
    borderColor: '#4338CA',
    freeSpaceBackgroundColor: '#E0E7FF',
    freeSpaceFontColor: '#4338CA',
    cellTextColor: '#1E1B4B',
    subtitleColor: '#312E81',
    borderWidth: 1.0,
    gridBorderRadius: 12,
    cellBackgroundMode: 'white',
    cellBackgroundTint: '#f8fafc',
    gradientDirection: 'horizontal',
    cardMatEnabled: true,
    backgroundPattern: null,
    backgroundPatternOpacity: 0.15
  }
];

export const getThemeById = (id) => {
  return themes.find(theme => theme.id === id) || null;
};

export const applyTheme = (theme, setters) => {
  const {
    setTitleFont,
    setTitleColor,
    setCellFont,
    setBackgroundColor,
    setUseGradient,
    setGradientColor1,
    setGradientColor2,
    setBorderColor,
    setFreeSpaceBackgroundColor,
    setFreeSpaceFontColor,
    setCellTextColor,
    setSubtitleColor,
    setBorderWidth,
    setGridBorderRadius,
    setCellBackgroundMode,
    setCellBackgroundTint,
    setGradientDirection,
    setGradientColor3,
    setCardMatEnabled,
    setBackgroundPattern,
    setBackgroundPatternOpacity
  } = setters;

  setTitleFont(theme.titleFont);
  setTitleColor(theme.titleColor);
  setCellFont(theme.cellFont);
  setBackgroundColor(theme.backgroundColor);
  setUseGradient(theme.useGradient);
  setGradientColor1(theme.gradientColor1);
  setGradientColor2(theme.gradientColor2);
  setBorderColor(theme.borderColor || '#1e40af');
  setFreeSpaceBackgroundColor(theme.freeSpaceBackgroundColor || '#dbeafe');
  setFreeSpaceFontColor(theme.freeSpaceFontColor || '#1e40af');
  
  setCellTextColor(theme.cellTextColor !== undefined ? theme.cellTextColor : '#1f2937');
  setSubtitleColor(theme.subtitleColor !== undefined ? theme.subtitleColor : '#4b5563');
  setBorderWidth(theme.borderWidth !== undefined ? theme.borderWidth : 1.5);
  setGridBorderRadius(theme.gridBorderRadius !== undefined ? theme.gridBorderRadius : 8);
  setCellBackgroundMode(theme.cellBackgroundMode !== undefined ? theme.cellBackgroundMode : 'white');
  setCellBackgroundTint(theme.cellBackgroundTint !== undefined ? theme.cellBackgroundTint : '#f8fafc');
  setGradientDirection(theme.gradientDirection !== undefined ? theme.gradientDirection : 'vertical');
  setGradientColor3(theme.gradientColor3 !== undefined ? theme.gradientColor3 : null);
  setCardMatEnabled(theme.cardMatEnabled !== undefined ? theme.cardMatEnabled : false);
  setBackgroundPattern(theme.backgroundPattern !== undefined ? theme.backgroundPattern : null);
  setBackgroundPatternOpacity(theme.backgroundPatternOpacity !== undefined ? theme.backgroundPatternOpacity : 0.15);
};
